# I need to refer nodejs tasks in common folder
# catalogue is one role
# common is also another role
# i need to import a task nodejs.yaml in catalogue

- name: install nodejs
  ansible.builtin.import_roles:
    name: common
    tasks_from: nodejs